# Scikit-learn Intro


## Resources

Notebook code based off on [scratch_work.ipynb](https://github.com/mori-c/meetups/blob/master/ds-to/helper/Machine%20Learning/Build%20a%20Complete%20Machine%20Learning%20Pipeline%20with%20scikit-learn/scratch%20work.ipynb)

#### Flow Charts

Scikit-Learn: Choosing the right estimator
[![scikit-learn flow chart](https://scikit-learn.org/stable/_static/ml_map.png)](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)

#### Documentations

- Pandas: [https://pandas.pydata.org/](https://pandas.pydata.org/pandas-docs/stable/)
- Scikit-Learn: [https://scikit-learn.org/](https://scikit-learn.org/stable/user_guide.html) / [PDF](https://scikit-learn.org/stable/_downloads/scikit-learn-docs.pdf)


## Helper File Directory

[meetups](https://github.com/mori-c/meetups) / [ds-to](https://github.com/mori-c/meetups/tree/master/ds-to) / [helper](https://github.com/mori-c/meetups/tree/master/ds-to/helper) / [Machine Learning](https://github.com/mori-c/meetups/tree/master/ds-to/helper/Machine%20Learning) / [Build a Complete Machine Learning Pipeline with scikit-learn](https://github.com/mori-c/meetups/tree/master/ds-to/helper/Machine%20Learning/Build%20a%20Complete%20Machine%20Learning%20Pipeline%20with%20scikit-learn) /

<br />


- ds-to/helper/**scikit-learn-pipeline.ipynb**
- ds-to/helper/**readme.md**
- ds-to/**helper**
---
- helper/**Machine Learning**
- helper/Machine Learning/**Build a Complete Machine Learning Pipeline with scikit-learn**/
    - helper/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/**data**
        - helper/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/data/**data_description.txt**
        - helper/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/data/**test.csv**
        - helper/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/data/**train.csv**
    - helper/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/**Custom Estimator.ipynb**
    - helper/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/**scratch work.ipynb**

<!--
```
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/data
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/data/data_description.txt
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/data/test.csv
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/data/train.csv
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/Custom\ Estimator.ipynb
ds-to/helper/Machine\ Learning/Build\ a\ Complete\ Machine\ Learning\ Pipeline\ with\ scikit-learn/scratch\ work.ipynb
```
-->

### Prompt

- split data
- group by join
- col transform
- validate by grid search
- predictive 


<br />

### Shortcuts
- migrate cell content together = esc + shift + m

In [37]:
# set_option(display): 

import pandas as pd
pd.set_option('display.max_columns', 100)

housing = pd.read_csv('/Users/moric/sand/active/meetups/ds-to/helper/Data-Science-Tutorials/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/Data/train.csv')
housing.head()
housing.shape

ids = housing.pop('Id').values
# y = housing.pop
y = housing.pop('SalePrice').values
Id[:5]
y[:5]
# y.head()
# y.
# y:[]

NameError: name 'Id' is not defined

In [38]:
print(open('/Users/moric/sand/active/meetups/ds-to/helper/Data-Science-Tutorials/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/Data/data_description.txt').read())

MSSubClass: Identifies the type of dwelling involved in the sale.	

        20	1-STORY 1946 & NEWER ALL STYLES
        30	1-STORY 1945 & OLDER
        40	1-STORY W/FINISHED ATTIC ALL AGES
        45	1-1/2 STORY - UNFINISHED ALL AGES
        50	1-1/2 STORY FINISHED ALL AGES
        60	2-STORY 1946 & NEWER
        70	2-STORY 1945 & OLDER
        75	2-1/2 STORY ALL AGES
        80	SPLIT OR MULTI-LEVEL
        85	SPLIT FOYER
        90	DUPLEX - ALL STYLES AND AGES
       120	1-STORY PUD (Planned Unit Development) - 1946 & NEWER
       150	1-1/2 STORY PUD - ALL AGES
       160	2-STORY PUD - 1946 & NEWER
       180	PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
       190	2 FAMILY CONVERSION - ALL STYLES AND AGES

MSZoning: Identifies the general zoning classification of the sale.
		
       A	Agriculture
       C	Commercial
       FV	Floating Village Residential
       I	Industrial
       RH	Residential High Density
       RL	Residential Low Density
       RP	Residential Low Density Park 
       RM

In [39]:
# clasdifications
# cat or continuous

cat_cols = ['Neighborhood', 'RoofStyle']
num_cols = ['OverallQual', 'OverallCond']
print('cat_cols: ', cat_cols)
print('num_cols: ', num_cols)

cat_cols:  ['Neighborhood', 'RoofStyle']
num_cols:  ['OverallQual', 'OverallCond']


In [40]:
# 3 STEP ESTIMATOR PROCESS
# scikit-learn object estimator (or transformers)
# learns from data, eg linear regressor of coefficients
# fitting === learning processing

num_cols = ['OverallQual', 'OverallCond']
df = housing[num_cols]
df.head(3)

OverallQual  OverallCond
0            7            5
1            6            8
2            7            5

In [41]:
df.isna().sum()

OverallQual    0
OverallCond    0
dtype: int64

In [42]:
# 01
# est == camel case
# trans ==

import sklearn
sklearn.__version__
# find SVN, neighbors, esemables

from sklearn.linear_model import LinearRegression


In [43]:
# 02 - instantiation type build
# constructor == build

# hyper parameters() = shift x tab twice

# variable = object(hyper param)
lr = LinearRegression()

In [44]:
# 03 - fitting to learn
# y = sale price
lr.fit(df, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [45]:
# y = mb+x
# blue cmd = esc + a / b, dd = del
# green edit = 

# 04
lr.coef_

array([45408.43267524,  -370.00654346])

In [46]:
# 05
lr.intercept_

-93976.22856801507

In [47]:
# before ml, must transform data
# cat_cols = ['Neighborhood', 'RoofStyle']
# trace_back for dev errors

cat_cols
df_cat = housing[cat_cols]
df_cat.head(3)

Neighborhood RoofStyle
0      CollgCr     Gable
1      Veenker     Gable
2      CollgCr     Gable

In [48]:
# retrain model imported
lr.fit(df_cat, y)

ValueError: could not convert string to float: 'Gable'

In [49]:
# using pandas is ok, but
df_cat.isna().sum()

Neighborhood    0
RoofStyle       0
dtype: int64

In [58]:
# SET UP MODEL

# transformer
# 01

from sklearn.impute import SimpleImputer

# 02 - what to fill in
# most-frequent good for missing values
# collab interative = recommend 
# constant 
si = SimpleImputer(strategy = 'constant', fill_value = 'OTHER')

si.fit(df_cat)



SimpleImputer(copy=True, fill_value='OTHER', missing_values=nan,
       strategy='constant', verbose=0)

In [60]:
# return new object array transformed
x = si.fit_transform(df_cat)
print(x)

[['CollgCr' 'Gable']
 ['Veenker' 'Gable']
 ['CollgCr' 'Gable']
 ...
 ['Crawfor' 'Gable']
 ['NAmes' 'Hip']
 ['Edwards' 'Gable']]


In [101]:
# convert strings into number with 'one-hot encoding' of 0 or 1
# new estamtor transoformer
# for preprossing data still

from sklearn.preprocessing import OneHotEncoder

# 01
# false turns 
ohe = OneHotEncoder(sparse = False)
# quick and dirty way to check to check if all 0's
    # ohe = OneHotEncoder(sparse = False, handle_unknown = 'ignore')

# 02 - fit to learn 
ohe.fit(x)
ohe.categories_


[array(['Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr',
        'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel',
        'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown',
        'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber',
        'Veenker'], dtype=object),
 array(['Flat', 'Gable', 'Gambrel', 'Hip', 'Mansard', 'Shed'], dtype=object)]

In [66]:
# return array with 0 or 1
ohe.transform(x)


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [68]:
# reverse transform position
ohe.get_feature_names()

array(['x0_Blmngtn', 'x0_Blueste', 'x0_BrDale', 'x0_BrkSide',
       'x0_ClearCr', 'x0_CollgCr', 'x0_Crawfor', 'x0_Edwards',
       'x0_Gilbert', 'x0_IDOTRR', 'x0_MeadowV', 'x0_Mitchel', 'x0_NAmes',
       'x0_NPkVill', 'x0_NWAmes', 'x0_NoRidge', 'x0_NridgHt',
       'x0_OldTown', 'x0_SWISU', 'x0_Sawyer', 'x0_SawyerW', 'x0_Somerst',
       'x0_StoneBr', 'x0_Timber', 'x0_Veenker', 'x1_Flat', 'x1_Gable',
       'x1_Gambrel', 'x1_Hip', 'x1_Mansard', 'x1_Shed'], dtype=object)

In [71]:
# 03 - ready for ml
Xt = ohe.fit_transform(x)
Xt

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [63]:
# most frequent in each col
# fitting is learning, transforming hasn't taken place yet

si.statistics_

array(['OTHER', 'OTHER'], dtype=object)

In [91]:
# random forest regressor

from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators = 100)
rfr.fit(Xt, y)

# matrix must be in the same size
rfr.predict(Xt)


# above is a manual way of doing a pipeline


array([195124.48955143, 241549.19959901, 195124.48955143, ...,
       200384.32128273, 146623.51239547, 122576.91690561])

In [92]:
# matrix must be in the same size

rfr.predict(Xt)

array([195124.48955143, 241549.19959901, 195124.48955143, ...,
       200384.32128273, 146623.51239547, 122576.91690561])

In [108]:
# turn into pipeline to automate
# meta-estimator requires the instantiation process first

from sklearn.pipeline import Pipeline

# si = SimpleImputer(strategy = 'constant', fill_value = 'OTHER')
# ohe = OneHotEncoder(sparse = False)


# PREP FOR META EST. - FIT TRANSFORM PASSED TO EACH STEPS BELOW GIVING A TRAINED MODEL
# list out steps as a requirement
steps = [
    # step 01: 'assign name', obj
    ('inpute', si),
    # step 02: encode
    ('ohe', ohe),
    # last step is to predict
    # here it's Random, of instanted
    ('rfr', rfr)
]

# outline steps
# pipe is an instance of pipeline


# pipe = Pipeline(steps)
# pipe.fit(df_cat, y);

cat_pipe = Pipeline(steps)
cat_pipe.fit(df_cat, y);

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [103]:
# check if trained by reference label given

# pipe.named_steps()
pipe.predict(df_cat)

array([195279.45311316, 239853.77544678, 195279.45311316, ...,
       199526.22063433, 146279.32228172, 122813.34554433])

In [104]:
# read test set
# method below isn't to real-life

test = pd.read_csv('/Users/moric/sand/active/meetups/ds-to/helper/Data-Science-Tutorials/Machine Learning/Build a Complete Machine Learning Pipeline with scikit-learn/Data/test.csv')
df_cat_test = test[cat_cols]
test

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0     1461          20       RH         80.0    11622   Pave   NaN      Reg   
1     1462          20       RL         81.0    14267   Pave   NaN      IR1   
2     1463          60       RL         74.0    13830   Pave   NaN      IR1   
3     1464          60       RL         78.0     9978   Pave   NaN      IR1   
4     1465         120       RL         43.0     5005   Pave   NaN      IR1   
5     1466          60       RL         75.0    10000   Pave   NaN      IR1   
6     1467          20       RL          NaN     7980   Pave   NaN      IR1   
7     1468          60       RL         63.0     8402   Pave   NaN      IR1   
8     1469          20       RL         85.0    10176   Pave   NaN      Reg   
9     1470          20       RL         70.0     8400   Pave   NaN      Reg   
10    1471         120       RH         26.0     5858   Pave   NaN      IR1   
11    1472         160       RM         21.0     1680   Pave   NaN      Reg   
12    1473         160       RM         21.0     1680   Pave   NaN      Reg   
13    1474         160       RL         24.0     2280   Pave   NaN      Reg   
14    1475         120       RL         24.0     2280   Pave   NaN      Reg   
15    1476          60       RL        102.0    12858   Pave   NaN      IR1   
16    1477          20       RL         94.0    12883   Pave   NaN      IR1   
17    1478          20       RL         90.0    11520   Pave   NaN      Reg   
18    1479          20       RL         79.0    14122   Pave   NaN      IR1   
19    1480          20       RL        110.0    14300   Pave   NaN      Reg   
20    1481          60       RL        105.0    13650   Pave   NaN      Reg   
21    1482         120       RL         41.0     7132   Pave   NaN      IR1   
22    1483          20       RL        100.0    18494   Pave   NaN      IR1   
23    1484         120       RL         43.0     3203   Pave   NaN      Reg   
24    1485          80       RL         67.0    13300   Pave   NaN      IR1   
25    1486          60       RL         63.0     8577   Pave   NaN      IR1   
26    1487          60       RL         60.0    17433   Pave   NaN      IR2   
27    1488          20       RL         73.0     8987   Pave   NaN      Reg   
28    1489          20       FV         92.0     9215   Pave   NaN      Reg   
29    1490          20       FV         84.0    10440   Pave   NaN      Reg   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1429  2890          30       RM         50.0     7030   Pave   NaN      Reg   
1430  2891          50       RM         75.0     9060   Pave   NaN      Reg   
1431  2892          30  C (all)         69.0    12366   Pave   NaN      Reg   
1432  2893         190  C (all)         50.0     9000   Pave   NaN      Reg   
1433  2894          50  C (all)         60.0     8520   Grvl   NaN      Reg   
1434  2895         120       RM         41.0     5748   Pave   NaN      IR1   
1435  2896         120       RM         44.0     3842   Pave   NaN      IR1   
1436  2897          20       RL         69.0    23580   Pave   NaN      IR1   
1437  2898          90       RL         65.0     8385   Pave   NaN      Reg   
1438  2899          20       RL         70.0     9116   Pave   NaN      Reg   
1439  2900          80       RL        140.0    11080   Pave   NaN      Reg   
1440  2901          20       RL          NaN    50102   Pave   NaN      IR1   
1441  2902          20       RL          NaN     8098   Pave   NaN      IR1   
1442  2903          20       RL         95.0    13618   Pave   NaN      Reg   
1443  2904          20       RL         88.0    11577   Pave   NaN      Reg   
1444  2905          20      NaN        125.0    31250   Pave   NaN      Reg   
1445  2906          90       RM         78.0     7020   Pave   NaN      Reg   
1446  2907         160       RM         41.0     2665   Pave   NaN      Reg   
1447  2908          20       RL         58.0    10172   Pa

In [ ]:
num_cols

In [98]:
steps

[('inpute', SimpleImputer(copy=True, fill_value='OTHER', missing_values=nan,
         strategy='constant', verbose=0)),
 ('ohe', OneHotEncoder(categorical_features=None, categories=None,
         dtype=<class 'numpy.float64'>, handle_unknown='error',
         n_values=None, sparse=False)),
 ('rfr', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
             oob_score=False, random_state=None, verbose=0, warm_start=False))]

In [106]:
# continous

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline


# subtract the mean and brings it to 0
# Z score
si = SimpleImputer(strategy = 'mean')
ss = StandardScaler
rfr = RandomForestRegressor(n_estimators = 100)

steps = [
    ('inpute', si),
    ('ss', ss),
    ('rfr', rfr)
]


# si.fit(df_cat)

# ohe = OneHotEncoder(sparse = False)
# ohe.fit(x)
# ohe.categories_

# rfr.fit(Xt, y)

# rfr.predict(Xt)

cont_pipe = Pipeline(steps)
cont_pipe.fit(df_cat, y);

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [121]:

from sklearn.compose import ColumnTransformer

cont_pipe = Pipeline(steps)
cont_pipe.fit(df_cat, y);


# 3 itemin parallel
transformers = [
    # 'name of transform', colums, pipeline
    ('cat', cat_cols, cat_pipe),
    # col name applied
    ('cont', count_pipe, num_cols)
    # transformer actualized
]

# column transformer (list of name, transformer, column)
ct = ColumnTransformer()

    
# transform cate and num cols and join into array
# then do random forest

Xt = ct.fit_transform(housing)

final_steps = [
    ('t', t),
    ('rfr', rfr)
]

final_steps = Pipeline(final_steps)
final_steps.fit(housing, y);
# SAVE ABOVE ASIDE
# joblib.dump(final_pipe, 'model.sklearn')

# must wrap in another pieline to do ML

AttributeError: 'DataFrame' object has no attribute 'dtype'

NameError: name 'ct' is not defined

In [119]:
# put everything together as a

# PREDICT by applying what's been learned
final_steps.predict(test)


NameError: name 'final_steps' is not defined

In [114]:
# 
Xt.shape

(1460, 31)

In [116]:
# 
housing.shape

(1460, 79)

In [115]:
# scikit learn can't get names atm
ct.get_feature_names()


NameError: name 'ct' is not defined

In [122]:
import joblib

joblib.dump(final_pipe, 'model.sklearn')

ModuleNotFoundError: No module named 'joblib'

In [123]:
p = joblib.load('model.sklearn')

NameError: name 'joblib' is not defined